# pgadmin service is a useful [GUI] client.
version: '3.1'

services:
  pdb:
    image: postgres:12.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: parola01
      POSTGRES_USER: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      postgres-net:

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 8086:80
    environment:
      PGADMIN_DEFAULT_EMAIL: tdr@tdrs.ro
      PGADMIN_DEFAULT_PASSWORD: parola01
    volumes:
      - pgadmin-config:/var/lib/pgadmin
    networks:
      postgres-net:

volumes:
  postgres-data:
  pgadmin-config:


networks:
  postgres-net:
    external:
      name: postgres-net
