# local use only; server deployment uses a docker-compose file that is not in git
# you will find that file in /home/docker/${project}/...

version: '3.1'
services:
  infoeducatie:
    image: infoeducatie:latest
    container_name: infoeducatie
#    restart: always
    environment:
      - NETCORE_USER_UID=69
      - TZ=Europe/Bucharest
    env_file:
      - .docker.env
    ports:
      - 7600:7600
    networks:
      postgres-net:
    volumes:
      - ../persisted:/app/persisted
      

networks:
  postgres-net:
    external:
      name: postgres-net

