# local use only; server deployment uses a docker-compose file that is not in git
# you will find that file in /home/docker/${project}/...

version: '3.7'
services:
  infoeducatie:
    image: infoeducatie:latest
    container_name: infoeducatie
    #    restart: always
    environment:
      - TZ=Europe/Bucharest
      - VIRTUAL_HOST=infoeducatie.tdrs.ro
      - LETSENCRYPT_HOST=infoeducatie.tdrs.ro
    env_file:
      - .vars.env
    networks:
      postgres-net:
      web-net:
    volumes:
      - ../persisted:/app/persisted


networks:
  postgres-net:
    external:
      name: postgres-net
  web-net:
    external:
      name: web-net
